//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int IDFactura { get; set; }
        public Nullable<int> IDPago { get; set; }
        public Nullable<int> IDEstudiante { get; set; }
        public Nullable<int> MesesPagos { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual estudiante estudiante1 { get; set; }
        public virtual estudiante estudiante2 { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Pago Pago1 { get; set; }
    }
}
