//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.cs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.Facturas = new HashSet<Factura>();
            this.Facturas1 = new HashSet<Factura>();
        }
    
        public int IDPago { get; set; }
        public Nullable<int> IDEstudiante { get; set; }
        public int Inscripcion { get; set; }
        public int Mensualidad { get; set; }
        public string FechaPago { get; set; }
    
        public virtual estudiante estudiante { get; set; }
        public virtual estudiante estudiante1 { get; set; }
        public virtual estudiante estudiante2 { get; set; }
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual ICollection<Factura> Facturas1 { get; set; }
    }
}
